[[redirects]]
  from = "https://tramundbass.ch/*"
  to = "https://trambass.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tramundbass.ch/*"
  to = "https://trambass.net/:splat"
  status = 301
  force = true